version: "3"
services:
  springboot_bbs:
    container_name: springboot_bbs
    # image: openjdk:17-jdk
    image: challduck/springboot_bbs
    ports:
      - "8082:8082"
    # volumes:
    #   - ./springboot_bbs/workspace:/workspace
    restart: always
    command: /bin/bash
    stdin_open: true
    tty: true
    environment:
      - ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - SPRING_DATASOURCE_URL=jdbc:mysql://springboot_bbs_db:3306/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USER_NAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_USER_PASSWORD}
    depends_on:
      - springboot_db
    networks:
      - web-net
      - db-net
  springboot_db:
    container_name: springboot_bbs_db
    image: mysql:8.0.33
    ports:
      - "13308:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER_NAME}
      - MYSQL_PASSWORD=${DATABASE_USER_PASSWORD}
    networks:
      - db-net
networks:
  web-net:
    external: true
  db-net:
    external: true
