# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI/CD

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build
      
    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot_bbs:latest .

    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot_bbs:latest

    - name: transfer docker compose file
      run: scp -o StrictHostKeyChecking=no docker-compose.yaml ${{ secrets.SSH_HOST_NAME }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_HOST_NAME }}/springboot-bbs
      
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_HOST_NAME }}
        password: ${{ secrets.SSH_SECRET }}
        script: |
          cd /home/${{ secrets.SSH_HOST_NAME }}/springboot-bbs
          echo "${{ secrets.SSH_SECRET }}" | sudo -S docker-compose down
          echo "${{ secrets.SSH_SECRET }}" | sudo -S docker pull ${{ secrets.DOCKERHUB_USERNAME }}/springboot_bbs:latest
          echo "${{ secrets.SSH_SECRET }}" | sudo -S docker-compose up -d
          echo "${{ secrets.SSH_SECRET }}" | sudo -S docker exec -it springboot_bbs java -jar springboot.jar
          echo "${{ secrets.SSH_SECRET }}" | sudo -S docker image prune -f
